#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a \\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx reload